project:
  type: website
  output-dir: docs

website:
  title: "Serena DeStefani"
  navbar:
    left:
      - text: Research
        href: about.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Leadership
        href: leadership.qmd
      - text: Adventures
        href: adventures.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

